brew "bat"
brew "fd"
brew "fzf"
brew "htop"
brew "hub"
brew "neovim", args: ["HEAD"]
brew "openssl"
brew "postgresql"
brew "rcm"
brew "readline"
brew "ripgrep"
brew "sqlite3"
brew "the_silver_searcher"
brew "tmux"
brew "xz"
brew "zlib"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
