require('plugins')
require('dm-lsp-config')
require('settings')
require('dm-autopairs')
require('dm-statusline')
require('dm-treesitter')
require('dm-nvim-tree')
require('dm-nvim-noirbuddy')
require('dm-chafa-nvim')
require ('dm-copilot')
require('mappings')
require('functions')
